server:
  assets-path: /home/yggdrasil/.glance/assets
  port: 80

pages:
  - name: Startpage
    width: slim
    center-vertically: true
    columns:
      - size: full
        widgets:
          - type: search
            autofocus: true

          - type: monitor
            cache: 1m
            title: Services
            sites:
              - title: Gitea
                url: http://yggdrasil.headscale.com:8000/
                icon: /assets/gitea.svg
              - title: Filebrowser
                url: http://yggdrasil.headscale.com:8001/
                icon: /assets/filebrowser.svg
              - title: qBittorrent
                url: http://yggdrasil.headscale.com:8004/
                check-url: http://qbittorrent:8080
                icon: /assets/qbittorrent.png
              - title: Bitcoin Node Manager
                url: http://yggdrasil.headscale.com:8001/
                check-url: http://172.17.0.1:8001
                icon: /assets/bitcoin.png
              - title: Portainer
                url: http://yggdrasil.headscale.com:9000/
                check-url: http://172.17.0.1:9000
                icon: /assets/portainer.png
              - title: Firefly
                url: http://yggdrasil.headscale.com:8005/
                check-url: http://firefly:8080
                icon: /assets/firefly.png

          - type: bookmarks
            groups:
              - title: General
                links:
                  - title: Gmail
                    url: https://mail.google.com/mail/u/0/
                  - title: Amazon
                    url: https://www.amazon.com/
                  - title: Github
                    url: https://github.com/
              - title: Entertainment
                links:
                  - title: YouTube
                    url: https://www.youtube.com/
                  - title: Prime Video
                    url: https://www.primevideo.com/
                  - title: Disney+
                    url: https://www.disneyplus.com/
              - title: Social
                links:
                  - title: Reddit
                    url: https://www.reddit.com/
                  - title: Twitter
                    url: https://twitter.com/
                  - title: Instagram
                    url: https://www.instagram.com/
  - name: Overview
    columns:
      - size: small
        widgets:
          - type: calendar

          - type: rss
            limit: 10
            collapse-after: 3
            cache: 3h
            feeds:
              - url: http://feeds.bbci.co.uk/news/world/rss.xml
                title: BBC
              - url: http://feeds.foxnews.com/foxnews/latest
                title: FOX
              - url: https://www.nhk.or.jp/kikakubosyuu/info.xml
                title: NHK

          - type: twitch-channels
            channels:
              - KaiCenat
              - moistcr1tikal
              - DisguisedToast
              - Emiru
              - asmongold

          - type: releases
            show-source-icon: true
            repositories:
              - glanceapp/glance
              - firefly-iii/firefly-iii
              - usememos/memos
              - filebrowser/filebrowser
              - Mirobit/bitcoin-node-manager
              - linuxserver/docker-qbittorrent

      - size: full
        widgets:
          - type: hacker-news

          - type: videos
            style: grid-cards
            collapse-after-rows: 2
            channels:
              - UCQeRaTukNYft1_6AZPACnog # Asmondgold TV
              - UCzXwjTI6c6mVn6oui_p6oiw # SMii7Y
              - UCMwJJL5FJFuTRT55ksbQ4GQ # Asmondgold Clips
              - UCPbGiUt4Yu8EsaFM-KAmgjg # Grizzy
              - UCHL9bfHTxCMi-7vfxQ-AYtg # Abroad in Japan
              - UCjiXtODGCCulmhwypZAWSag # Jynxzi

          - type: reddit
            subreddit: selfhosted

          - type: reddit
            subreddit: NixOS

      - size: small
        widgets:
          - type: weather
            location: West Lafayette, Indiana, United States

          - type: markets
            markets:
              - symbol: BTC-USD
                name: Bitcoin
              - symbol: ETH-USD
                name: Ethereum
              - symbol: XRP-USD
                name: Ripple XRP
              - symbol: SOL-USD
                name: Solana
              - symbol: ADA-USD
                name: Cardano
              - symbol: SUI20947-USD
                name: Sui
              - symbol: TON-USD
                name: The Open Network
              - symbol: ZEC-USD
                name: ZCash
