name: "flake-updater"

on:
  workflow_dispatch:
  schedule:
    - cron: "14 0 * * 0"

jobs:
  nix-flake-update:
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: wimpysworld/nothing-but-nix@v6
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/determinate-nix-action@v3
      - uses: DeterminateSystems/update-flake-lock@v25
        with:
          pr-title: "weekly update of flake inputs - ${{ github.event.repository.updated_at}}"
          pr-labels: |
            dependencies
            automated
          token: ${{ secrets.GH_TOKEN }}
